name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
port: 4444
baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
